### PR TITLE
Add Scala support

### PR DESCRIPTION
**Pull request by hpwxf**
With a scala code sample (screenshot done with Dracula theme):

Screenshot:
Capture d’écran 2019-03-24 à 20 06 39

Code sample:
[ScalaSyntaxDemo.txt](https://github.com/EnlighterJS/EnlighterJS/files/3000736/ScalaSyntaxDemo.txt)

### CODE REVIEW

**Comment by AndiDittrich** [comment]
thanks @hpwxf 

i will check your pull request soon. 

btw. the license header is invalid

**Comment by hpwxf** [comment]
Ok, I will fix header.

Types that I've associated with regex seem to be not conform to how they are used in other languages like java (I will fix that to be more homogeneous -- my first idea was to mimic IntelliJ highlighting but I seems to be better to make my own theme for that).

Moreover, I saw that type 's9' used for annotation in C++, C# and Java is never declared in any theme. Is-it a bad type or a missing type in themes ?

**Comment by AndiDittrich** [comment]
thanks for the hint - the token `s9` is missing in the themes+docs - it was projected to be used for annotations or special strings.

**token definitions**
in general, a language support file has to exactly match the [token definitions](https://github.com/EnlighterJS/docs/blob/master/HighlightingEngine_and_Symbols.md) - otherwise the themes will look different for each language

**header**
please add your name to the license header as author - this will clearly state that the committed content is under the MPL-2.0

**Comment by hpwxf** [comment]
I fixed the code according to your remarks. If you see any other useful improvement, tell me.

**Comment by AndiDittrich** [comment]
the "type" (`k5`) seems to be redundant

**Comment by hpwxf** [comment]
Yes, there are 3 regex for "type" (k5).
- one for all basic types: regex: /\b(Boolean|Byte|Int|Long|Float|Double|Char|String|Unit)\b/g
- one following the type naming convention : regex: /\b([A-Z]\w*)\b/g
- one for type in generic class : regex: /\[\s*([-+]?[A-Z]\w*)\s*\]/g
I split it to explicit basic types (if it may be relevant to use a different highlighting) and types in generic to include variance qualifier (+ or -). If you prefer, I can use only the second one (the type naming convention).

**Comment by AndiDittrich** [comment]
ok.. i will change this soon. it has a significant performance impact using redundant rulesets

**Pull request merged**
